### ISSUE TITLE
Prime cruncher written in C

### ISSUE THREAD

**Issue by JL2210** [blu/euclid#1]
crunch_results.c
```
#define TRUE 1
#define FALSE 2
#define ERR 3

int crunch_results( int results )
{
	unsigned long long ctr;

	if ( results == 2 )
	{
		return TRUE;
	}
	else if ( results > 2 )
	{
		return FALSE;
	}
	else
	{
		return ERR;
	}
}
```
prime_crunch.c
```
#define TRUE 1
#define FALSE 2
#define ERR 3

extern int crunch_results( int );

int prime_crunch( unsigned long long nbr )
{
	unsigned long long ctr;
	int results = 0;
	int result = 0;

	for ( ctr = 1; ctr <= nbr; ctr++ )
	{
		if ( nbr > 2 && (nbr % 2) == 0 )
		{
			return FALSE;
		}
		else if ( (nbr % ctr) == 0 )
		{
			results++;
		}
	}

	result = crunch_results(results);
	return result;
}
```
main.c
```
#include <stdio.h>

extern int prime_crunch( unsigned long long );

#define TRUE 1
#define FALSE 2
#define ERR 3

int main()
{
	int result;
	unsigned long long ctr, nbr;

	for( ctr = 1;; ctr++ )
	{
		nbr = ctr;
		result = prime_crunch(nbr);
		if ( result == TRUE )
		{
			printf("%llu is a prime number\n", nbr);
		}
		else if ( result == FALSE )
		{
			printf("%llu is not a prime number\n", nbr);
		}
		else if ( result == ERR )
		{
			printf("%llu is neither prime nor composite\n", nbr);
		}
		else
		{
			printf("Error in line %lu\n", __LINE__);
			return ERR;
		}
	}
	return ERR + 1;
}
```

**Comment by blu** [comment]
@JL2210 A tip: consider whether you need to seek divisors through all natural numbers smaller than N.

**Comment by JL2210** [comment]
I don't, however if I only calculate half the numbers, 1 will have to have a special exception. I don't want to have to resort to doing that.

**Comment by blu** [comment]
Let's forget about 1 for a sec. Think of the reason why you can reduce to half the numbers when looking for divisors -- because half the numbers would be multiples of 2, and you've already checked for divisibility by 2 early on -- you have an early-out check for that. Now, what *other* multiples could we have before N, and can you do an "early-out" for those? I suggest you check out what the [Sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes) does, as it's innately related to any first-principles primes-seeking algorithm.

**Comment by JL2210** [comment]
I have an idea. Would it help if I started from one and worked up?
